version: '3'

services:
  energy-api:
    build:
      context: .
    ports:
      - "8282:8282"
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default